export enum ActionType {
	LOAD_IMAGES = 'LOAD_IMAGES',
    LOAD_IMAGES_ERROR = 'LOAD_IMAGES_ERROR',
	ARCHIVE_IMAGE = 'ARCHIVE_IMAGE',
	// ADD_IMAGE = 'ADD_IMAGE',
	// REMOVE_IMAGE = 'REMOVE_IMAGE',
	LOAD_USERS = 'LOAD_USERS',
}
