export enum ActionType {
	LOAD_IMAGES = 'LOAD_IMAGES',
    LOAD_IMAGES_ERROR = 'LOAD_IMAGES_ERROR',
	// LOAD_IMAGES_SUCESS = 'LOAD_IMAGES_SUCESS',
	// ADD_IMAGE = 'ADD_IMAGE',
	// ARCHIVE_IMAGE = 'ARCHIVE_IMAGE',
	// REMOVE_IMAGE = 'REMOVE_IMAGE',
}
